version: '3'

services:
    python:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/powertofly
        ports:
            - 8000:8000
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=users
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=rupal123